name: Testing

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12
        activate-environment: snakemake-env
        channels: conda-forge,bioconda

    - name: Install Snakemake and tools
      run: |
        conda activate snakemake-env
        conda install -c conda-forge -c bioconda snakemake=8.10.0
      shell: bash -l {0}

    - name: Unzip input files
      run: gzip -d test_data/chr7.fa.gz

    - name: Clean previous conda envs
      run: rm -rf .snakemake/conda

    - name: Run Snakemake
      run: |
        conda activate snakemake-env
        snakemake -s workflow/snakefile_final.smk --use-conda --rerun-incomplete --cores 2 -k --conda-frontend conda
      shell: bash -l {0}