name: Testing

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
    Testing:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Create conda packages directory
        run: mkdir -p $HOME/conda_pkgs_dir
      - name: Install dependencies
        run: |
          export CONDA_PKGS_DIRS=$HOME/conda_pkgs_dir
          conda install -c conda-forge -c bioconda snakemake
          conda install -c conda-forge python=3.10
      - name: Setup snakemake
        run: |
          mamba install -c conda-forge -c bioconda snakemake
      - run: echo "Finish installing snakemake"
      - name: unzip the files
        run: |
           gzip -d test_data/chr7.fa.gz
      - name: Run snakemake
        run: snakemake -s workflow/snakefile_final.smk --use-conda --rerun-incomplete --core 2 -k